---
parser: "@typescript-eslint/parser"
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
env:
  browser: true
  es6: true
  jest: true
  node: true
root: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
rules:
  comma-dangle: off
  "@typescript-eslint/comma-dangle": off
  # React Rules
  react/prop-types: off
  # .defaultProps deprecated for functional components
  react/require-default-props: off
  react/display-name: 'off'
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'
  react/prefer-stateless-function: 'off'
  # defaultProps deprecated so if you use classes just use static
  react/static-property-placement:
    - error
    - 'static public field'
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-props-no-spreading: off
  # Imports Rules
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/prefer-default-export: off
  no-underscore-dangle: off
  # Typescript Rules
  "@typescript-eslint/explicit-function-return-type": 'off'
  "@typescript-eslint/interface-name-prefix": 'off'
  "@typescript-eslint/ban-ts-comment": error
  "@typescript-eslint/no-non-null-assertion": 'off'
  "@typescript-eslint/explicit-module-boundary-types": 'off'
  "@typescript-eslint/no-empty-function": 'off'
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-var-requires": 'off'
  "@typescript-eslint/naming-convention": off
  # Redux
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - 'state'
settings:
  react:
    pragma: React
    version: detect
ignorePatterns:
  - "**/*.css"
  - "vite.config.ts"
  - "node_modules"
  - "dist"
  - "coverage"
  - "dist"
  - "server.ts"
  - "cypress"
  - "cypress.config.ts"
...
